### ISSUE TITLE
Using this project in other projects

### ISSUE THREAD

**Issue by sparse91** [gaborbata/groovy-web-console#1]
Hi
Is there any way to use this project in other spring projects without copy & pasting the source? Like maven dependencies? or if you know similar project?
Thank you

**Comment by gaborbata** [comment]
Hi @sparse91, sorry for the late answer. Currently it is not available as a dependency, and it is unlikely I will implement that. I am not aware of similar projects, but feel free to contribute. :)

Regards, Gabor
